apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: pingfederate-cluster-upgrade
  labels:
    role: pingfederate
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: bind-port
      port: 7600
      protocol: TCP
    - name: fail-port
      port: 7700
      protocol: TCP
  selector:
    role: pingfederate
