
apiVersion: v1
kind: Service
metadata:
  name: pingfederate-admin
  labels:
    role: pingfederate
    tier: console
    version: 10.1.5
spec:
  ports:
  - name: console
    port: 9999
  selector:
    role: pingfederate
    tier: console
    version: 10.1.5
